module.exports = {
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  CREDENTIALS_IVALID: 'CREDENTIALS_IVALID',
  USER_DISABLED: 'USER_DISABLED',
  NOT_MODEL: 'NOT_MODEL',
  PAGE_MUST_BE_A_NUMBER: 'PAGE_MUST_BE_A_NUMBER',
  CART_BELONGS_OTHER_USER: 'CART_BELONGS_OTHER_USER',
  SHOPPING_CART_DATA_NEEDIT: 'SHOPPING_CART_DATA_NEEDIT',
  PRODUCT_ID_NEEDIT: 'PRODUCT_ID_NEEDIT',
  // Successful
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
};
